# Name helps to make reader understand what is about to come
name: Pipeline for Node.js on Github Action

# It tells when to start analysing and testing code
on: push

# Contains the main work to be done
jobs:
  git-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"

  bubye:
    runs-on: ubuntu-latest
    steps:
      - name: Bye World
        run: echo "Bubye World"